# Generated by Django 5.1.3 on 2025-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_biometrics_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='customuser',
            name='voice_mode',
            field=models.BooleanField(default=False),
        ),
    ]
